### ISSUE TITLE
android studio 3.0 can't build

### ISSUE THREAD

**Issue by IvanGarza07** [hoang8f/android-flat-button#40]
this is the error that android studio 3.0 show when run the project 

Error inflating class info.hoang8f.widget.FButton

Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x5                                                                                
 at android.content.res.TypedArray.getColor(TypedArray.java:463)
 at info.hoang8f.widget.FButton.parseAttrs(FButton.java:116)

**Comment by Shaafi20** [comment]
Well I think the problem is with the android gradle plugin version. Try changing it to 2.3.3 in File -> Project Structure -> Project. It worked for me.

**Comment by Abdulwahid80** [comment]
I have the same problem and I have solved it by changing the build gradle to 2.3.3 but still doesn't work.
Also I have delete -google()- from build script repositories and allprojects repositories and it works perfectly. I don't know what the problem exactly or why adding google() repository cause this problem?

**Comment by Kin-AppDev** [comment]
Can someone describe the details on how to create that attrs.xml file (which qualifiers should one use?) to the values folder before copy & paste to it? Thanks
