### ISSUE TITLE
i have this error and cause my progam to crash

### ISSUE THREAD

**Issue by Jsamouil** [hoang8f/android-flat-button#51]
2020-02-02 12:00:21.504 16953-16953/com.example.fastfood1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.fastfood1, PID: 16953
    android.view.InflateException: Binary XML file line #12: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.example.fastfood1.Adapter.MyBeastDealsAdapter.inflateView(MyBeastDealsAdapter.java:38)
        at com.asksira.loopingviewpager.LoopingPagerAdapter.instantiateItem(LoopingPagerAdapter.java:76)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:540)
        at com.asksira.loopingviewpager.LoopingViewPager.setAdapter(LoopingViewPager.java:214)
        at com.example.fastfood1.ui.home.HomeFragment.lambda$onCreateView$1$HomeFragment(HomeFragment.java:57)
        at com.example.fastfood1.ui.home.-$$Lambda$HomeFragment$08hSC5SwHI-e3mXM6hOsJKuNgEI.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.example.fastfood1.ui.home.HomeViewModel.onBestDealLoadSuccess(HomeViewModel.java:123)
        at com.example.fastfood1.ui.home.HomeViewModel$1.onDataChange(HomeViewModel.java:60)
        at com.google.firebase.database.Query$1.onDataChange(com.google.firebase:firebase-database@@19.2.0:179)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@19.2.0:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@19.2.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.2.0:55)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by beartistic** [comment]
+1
